import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import {webcrypto} from 'node:crypto';
const event=()=>({listeners:[],addListener(fn){this.listeners.push(fn)},emit(...args){for(const fn of this.listeners)fn(...args)}});
const descriptor={vendorId:0x05f3,productId:0xff,name:'Fixture pedal',signature:'[[1,0,[0]]]'};
const device={vendorId:descriptor.vendorId,productId:descriptor.productId,productName:descriptor.name,collections:[{usagePage:1,usage:0,inputReports:[{reportId:0}],children:[]}],opened:false,async open(){this.opened=true},async close(){this.opened=false},addEventListener(type,fn){if(type==='inputreport')reportHandler=fn;},removeEventListener(){reportHandler=null;}};
let reportHandler;const injections=[];
let stored={},actions=0;
const chrome={runtime:{id:'fixture',getURL:p=>`chrome-extension://fixture/${p}`,getManifest:()=>({version:'0.1.8'}),onMessage:event(),onConnect:event()},storage:{local:{async get(){return structuredClone(stored)},async set(value){stored=structuredClone(value)}}},action:{async setBadgeText(){}},windows:{async getLastFocused(){return {id:1,focused:true}},onFocusChanged:event()},tabs:{onRemoved:event(),onActivated:event(),onUpdated:event(),async query(){return [{id:1,windowId:1,url:'https://example.test/'}]}},permissions:{onRemoved:event(),async contains(){return true}},scripting:{async executeScript(request){injections.push(request);actions++;return [{frameId:0,result:{ok:true}}]}}};
const hid={async getDevices(){return [device]},addEventListener(){}};
vm.runInNewContext(await readFile('dist-extension/background.js','utf8'),{chrome,navigator:{hid},crypto:webcrypto,TextEncoder,structuredClone,performance,Date,URL,Uint8Array,setTimeout,clearTimeout,setInterval,clearInterval,queueMicrotask,console});
const sender={id:'fixture',url:'chrome-extension://fixture/popup.html'};
const send=m=>new Promise(resolve=>{assert.equal(chrome.runtime.onMessage.listeners[0](m,sender,resolve),true);});
let rejectedReply=false;assert.equal(chrome.runtime.onMessage.listeners[0]({type:'native',command:'open'},{id:'other',url:'https://evil.test'},()=>{rejectedReply=true}),false);assert.equal(rejectedReply,false);
assert.equal((await send({type:'connect',device:descriptor})).ok,true);assert.equal(device.opened,true);assert.equal((await send({type:'state'})).state.config.enabled,false);await send({type:'enabled',value:true});
assert.equal((await send({type:'state'})).state.config.rightClickGuard,false);
assert.equal((await send({type:'rightClickGuard',value:'yes'})).ok,false);
assert.equal((await send({type:'rightClickGuard',value:true})).ok,true);
const config=(await send({type:'state'})).state.config;
for(const mapping of Object.values(config.mappings))mapping.action='none';
await send({type:'mappings',mappings:config.mappings});
const report=value=>reportHandler({device,reportId:0,data:new DataView(Uint8Array.from([value,0]).buffer)});
report(0);const pressedAt=Date.now();report(2);
await new Promise(resolve=>setTimeout(resolve,5));
assert.equal(injections.length,1,'guard also applies to Do nothing');
assert.equal(injections[0].target.allFrames,true);assert.ok(injections[0].args[0]>=pressedAt+250&&injections[0].args[0]<=Date.now()+250);
await send({type:'rightClickGuard',value:false});assert.equal(injections.at(-1).args[0],0,'disable clears existing guard');
report(0);const before=injections.length;report(2);await new Promise(resolve=>setTimeout(resolve,5));assert.equal(injections.length,before,'disabled guard never injects');
assert.equal((await send({type:'native',command:'open'})).ok,false,'obsolete helper commands rejected');
await send({type:'disconnect'});assert.equal(device.opened,false);
assert.equal((await send({type:'connect',device:descriptor})).ok,true);
chrome.permissions.onRemoved.emit({origins:['https://example.test/*']});
await send({type:'disconnect'});
assert.equal((await send({type:'state'})).state.connected,false);
console.log('PASS browser worker: sender trust, guard settings, Do nothing guarding, disable, removed helper commands and disconnect.');
