import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import {webcrypto} from 'node:crypto';
const event=()=>({listeners:[],addListener(fn){this.listeners.push(fn)},emit(...args){for(const fn of this.listeners)fn(...args)}});
const descriptor={vendorId:0x05f3,productId:0xff,name:'Fixture pedal',signature:'[[1,0,[0]]]'};
const device={vendorId:descriptor.vendorId,productId:descriptor.productId,productName:descriptor.name,collections:[{usagePage:1,usage:0,inputReports:[{reportId:0}],children:[]}],opened:false,async open(){this.opened=true},async close(){this.opened=false},addEventListener(type,fn){if(type==='inputreport')reportHandler=fn;},removeEventListener(){reportHandler=null;}};
let reportHandler;const injections=[];
let permission=false,stored={},actions=0,nativeConnections=0,port;
const state={capturing:false,enabled:false,learning:null,learned:[],held:0,presses:0};
const chrome={runtime:{id:'fixture',getURL:p=>`chrome-extension://fixture/${p}`,getManifest:()=>({version:'0.1.5'}),onMessage:event(),onConnect:event(),connectNative(){nativeConnections++;port={onMessage:event(),onDisconnect:event(),disconnect(){this.onDisconnect.emit()},postMessage(m){if(m.type==='start')state.capturing=true;if(m.type==='stop')state.capturing=false;queueMicrotask(()=>port.onMessage.emit({id:m.id,ok:true,state:{...state},devices:[]}));}};return port;}},storage:{local:{async get(){return structuredClone(stored)},async set(value){stored=structuredClone(value)}}},action:{async setBadgeText(){}},windows:{async getLastFocused(){return {id:1,focused:true}},onFocusChanged:event()},tabs:{onRemoved:event(),onActivated:event(),onUpdated:event(),async query(){return [{id:1,windowId:1,url:'https://example.test/'}]}},permissions:{onRemoved:event(),async contains(m){return m.permissions?permission:true}},scripting:{async executeScript(request){injections.push(request);actions++;return [{frameId:0,result:{ok:true}}]}}};
const hid={async getDevices(){return [device]},addEventListener(){}};
vm.runInNewContext(await readFile('dist-extension/background.js','utf8'),{chrome,navigator:{hid},crypto:webcrypto,TextEncoder,structuredClone,performance,Date,URL,Uint8Array,setTimeout,clearTimeout,setInterval,clearInterval,queueMicrotask,console});
const sender={id:'fixture',url:'chrome-extension://fixture/native.html'};
const send=m=>new Promise(resolve=>{assert.equal(chrome.runtime.onMessage.listeners[0](m,sender,resolve),true);});
let rejectedReply=false;assert.equal(chrome.runtime.onMessage.listeners[0]({type:'native',command:'open'},{id:'other',url:'https://evil.test'},()=>{rejectedReply=true}),false);assert.equal(rejectedReply,false);
assert.equal((await send({type:'connect',device:descriptor})).ok,true);assert.equal(device.opened,true);
assert.equal((await send({type:'state'})).state.config.rightClickGuard,false);
assert.equal((await send({type:'rightClickGuard',value:'yes'})).ok,false);
assert.equal((await send({type:'rightClickGuard',value:true})).ok,true);
const config=(await send({type:'state'})).state.config;
for(const mapping of Object.values(config.mappings))mapping.action='none';
await send({type:'mappings',mappings:config.mappings});
const report=value=>reportHandler({device,reportId:0,data:new DataView(Uint8Array.from([value,0]).buffer)});
report(0);const pressedAt=Date.now();report(2);
await new Promise(resolve=>setTimeout(resolve,5));
assert.equal(injections.length,1,'guard also applies to Do nothing');
assert.equal(injections[0].target.allFrames,true);assert.ok(injections[0].args[0]>=pressedAt+250&&injections[0].args[0]<=Date.now()+250);
await send({type:'rightClickGuard',value:false});assert.equal(injections.at(-1).args[0],0,'disable clears existing guard');
report(0);const before=injections.length;report(2);await new Promise(resolve=>setTimeout(resolve,5));assert.equal(injections.length,before,'disabled guard never injects');
actions=0;
assert.equal((await send({type:'native',command:'open'})).ok,false);assert.equal(nativeConnections,0);assert.equal(device.opened,true);
permission=true;assert.equal((await send({type:'native',command:'open'})).ok,true);assert.equal(nativeConnections,1);assert.equal(device.opened,false);assert.equal(stored.config.autoConnect,false);
assert.equal((await send({type:'connect',device:descriptor})).ok,false,'no second WebHID reader');
assert.equal((await send({type:'native',command:'start',token:'opaque',reviewed:true})).ok,true);assert.equal(actions,0,'no duplicate DOM actions');
assert.equal((await send({type:'native',command:'shell'})).ok,false);
chrome.permissions.onRemoved.emit({permissions:['nativeMessaging']});assert.equal((await send({type:'state'})).state.native.connected,false,'revoking native permission releases the connection');
assert.equal((await send({type:'native',command:'close'})).ok,true);assert.equal((await send({type:'state'})).state.native.connected,false);
assert.equal((await send({type:'connect',device:descriptor})).ok,true);
let releaseSave;const originalSave=chrome.storage.local.set;
chrome.storage.local.set=async value=>{await new Promise(resolve=>{releaseSave=resolve;});await originalSave(value);};
const opening=send({type:'native',command:'open'});await new Promise(resolve=>setTimeout(resolve,0));
assert.equal((await send({type:'connect',device:descriptor})).ok,false,'reader blocked while native mode is being prepared');
chrome.storage.local.set=originalSave;releaseSave();assert.equal((await opening).ok,true);await send({type:'native',command:'close'});await send({type:'disconnect'});
console.log('PASS native worker: sender trust, optional permission, reader isolation, no auto-recapture, command whitelist and browser-mode recovery.');
